if strcmp(TransferLearning,'True')

    if strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True') && strcmp(add_depth,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Dh_Site_SoF_Reg',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_vs30,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True') && strcmp(add_depth,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Vs30_Dh_SoF_Reg',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Site_SoF_Reg',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True') && strcmp(add_depth,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Dh_Site_SoF',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_vs30,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Vs30_SoF_Reg',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Site_SoF',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_vs30,'True') && strcmp(add_fm,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Vs30_SoF',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Site',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Mw_logRjb_Site',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%_s%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_logRjb',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_m,'True') && strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Mw_logRjb',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_distance,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_m,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Mw',dbn_name,'TL',verNet)),'NNs');
    elseif strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'logRjb',dbn_name,'TL',verNet)),'NNs');
    else
        save(fullfile(wd,sprintf('net _%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,dbn_name,'TL',verNet)),'NNs');
    end

else

    if strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True') && strcmp(add_depth,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Dh_Site_SoF_Reg',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_vs30,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True') && strcmp(add_depth,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Vs30_Dh_SoF_Reg',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Site_SoF_Reg',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True') && strcmp(add_depth,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Dh_Site_SoF',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_vs30,'True') && strcmp(add_fm,'True') && strcmp(separate_regions,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Vs30_SoF_Reg',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True') && strcmp(add_fm,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Site_SoF',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_vs30,'True') && strcmp(add_fm,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Vs30_SoF',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(separate_classes,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_Site',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True') && strcmp(add_fm,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb_SoF',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True') && strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw_logRjb',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_m,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_Mw',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True') && strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb_logRjb',dbn_name,verNet)),'NNs');
    elseif strcmp(add_m,'True') && strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Mw_logRjb',dbn_name,verNet)),'NNs');
    elseif strcmp(add_distance,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Rjb',dbn_name,verNet)),'NNs');
    elseif strcmp(add_lndistance,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'logRjb',dbn_name,verNet)),'NNs');
    elseif strcmp(add_m,'True')
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,'Mw',dbn_name,verNet)),'NNs');
    else
        save(fullfile(wd,sprintf('net_%u_%s_%s_%s.mat',...
            round(ann.TnC*100) ,ann.cp,dbn_name,verNet)),'NNs');
    end
end